#
# pScheduler Dev Host Configuration
#

# Private network used by the dev machines
private_network_v4: 10.0.0.0/28
private_network_v6: fc00::/124

# Machine number.  This must be within the number of usable hosts in
# private_network (e.g., 1-254 for an IPv4 /24).
host_number: 4
